import { index, layout, type RouteConfig, route } from "@react-router/dev/routes";

export default [
  route("health", "routes/health.ts"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("api/organisation-switch", "routes/api.organisation-switch.ts"),
  route("api/consumer-secret/:id", "routes/api.consumer-secret.$id.ts"),
  route("api/consumer-apikey/:id", "routes/api.consumer-apikey.$id.ts"),
  route("api/consumer-token/:id", "routes/api.consumer-token.$id.ts"),
  route("api/consumer-proxy", "routes/api.consumer-proxy.ts"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  layout("routes/layout.tsx", [
    index("routes/home.tsx"),
    route("organisation", "routes/organisation.tsx"),
    route("apis", "routes/apis.tsx"),
    route("apis/new", "routes/api-create.tsx"),
    route("apis/:id", "routes/apis.$id.tsx"),
    route("products", "routes/products.tsx"),
    route("products/new", "routes/product-create.tsx"),
    route("products/:id", "routes/products.$id.tsx"),
    route("environments", "routes/environments.tsx"),
    route("plans", "routes/plans.tsx"),
    route("consumers", "routes/consumers.tsx"),
    route("consumers/new", "routes/consumer-create.tsx"),
    route("consumers/:id", "routes/consumers.$id.tsx"),
    route("consumers/:id/tryout", "routes/consumers.$id.tryout.tsx"),
    route("domains", "routes/domains.tsx"),
    route("domains/new", "routes/domain-create.tsx"),
    route("domains/:id", "routes/domains.$id.tsx"),
  ]),
] satisfies RouteConfig;
